// File generated by FlutterFire CLI.
// ignore_for_file: type=lint
import 'package:firebase_core/firebase_core.dart' show FirebaseOptions;
import 'package:flutter/foundation.dart'
    show defaultTargetPlatform, kIsWeb, TargetPlatform;

/// Default [FirebaseOptions] for use with your Firebase apps.
///
/// Example:
/// ```dart
/// import 'firebase_options.dart';
/// // ...
/// await Firebase.initializeApp(
///   options: DefaultFirebaseOptions.currentPlatform,
/// );
/// ```
class DefaultFirebaseOptions {
  static FirebaseOptions get currentPlatform {
    if (kIsWeb) {
      return web;
    }
    switch (defaultTargetPlatform) {
      case TargetPlatform.android:
        return android;
      case TargetPlatform.iOS:
        return ios;
      case TargetPlatform.macOS:
        return macos;
      case TargetPlatform.windows:
        return windows;
      case TargetPlatform.linux:
        throw UnsupportedError(
          'DefaultFirebaseOptions have not been configured for linux - '
          'you can reconfigure this by running the FlutterFire CLI again.',
        );
      default:
        throw UnsupportedError(
          'DefaultFirebaseOptions are not supported for this platform.',
        );
    }
  }

  static const FirebaseOptions web = FirebaseOptions(
    apiKey: 'AIzaSyBhDnwh_xRPqiGq8QrZ1D8Eq2RESaO78Wc',
    appId: '1:1091819539761:web:58cc5c49c014ec3347b410',
    messagingSenderId: '1091819539761',
    projectId: 'gestion-gym-ae94c',
    authDomain: 'gestion-gym-ae94c.firebaseapp.com',
    storageBucket: 'gestion-gym-ae94c.firebasestorage.app',
    measurementId: 'G-CMHSX1J227',
  );

  static const FirebaseOptions android = FirebaseOptions(
    apiKey: 'AIzaSyAlBF4Q3rMIPXTsKBTBvLK5TmEuv07UStI',
    appId: '1:1091819539761:android:2e6f76c0fda7246347b410',
    messagingSenderId: '1091819539761',
    projectId: 'gestion-gym-ae94c',
    storageBucket: 'gestion-gym-ae94c.firebasestorage.app',
  );

  static const FirebaseOptions ios = FirebaseOptions(
    apiKey: 'AIzaSyAURuHOrYl4Oz191FPlM3-NIo9UCJkxuug',
    appId: '1:1091819539761:ios:4df1c49739d024cb47b410',
    messagingSenderId: '1091819539761',
    projectId: 'gestion-gym-ae94c',
    storageBucket: 'gestion-gym-ae94c.firebasestorage.app',
    iosBundleId: 'com.example.gestionGym',
  );

  static const FirebaseOptions macos = FirebaseOptions(
    apiKey: 'AIzaSyAURuHOrYl4Oz191FPlM3-NIo9UCJkxuug',
    appId: '1:1091819539761:ios:4df1c49739d024cb47b410',
    messagingSenderId: '1091819539761',
    projectId: 'gestion-gym-ae94c',
    storageBucket: 'gestion-gym-ae94c.firebasestorage.app',
    iosBundleId: 'com.example.gestionGym',
  );

  static const FirebaseOptions windows = FirebaseOptions(
    apiKey: 'AIzaSyBhDnwh_xRPqiGq8QrZ1D8Eq2RESaO78Wc',
    appId: '1:1091819539761:web:77dac70a2487469a47b410',
    messagingSenderId: '1091819539761',
    projectId: 'gestion-gym-ae94c',
    authDomain: 'gestion-gym-ae94c.firebaseapp.com',
    storageBucket: 'gestion-gym-ae94c.firebasestorage.app',
    measurementId: 'G-TRDKQZQH62',
  );
}
